-- MySQL Script generated by MySQL Workbench
-- Fri Jul 15 08:51:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categorieproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorieproduit` (
  `idCategorieProduit` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategorieProduit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `photoURL` VARCHAR(1000) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `conditionnement` VARCHAR(45) NULL DEFAULT NULL,
  `idCategorieProduit` INT NULL DEFAULT NULL,
  `visible` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduit`),
  INDEX `fk_Produit_CategorieProduit1_idx` (`idCategorieProduit` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_CategorieProduit1`
    FOREIGN KEY (`idCategorieProduit`)
    REFERENCES `categorieproduit` (`idCategorieProduit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalogue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogue` (
  `idCatalogue` INT NOT NULL AUTO_INCREMENT,
  `quantite` INT NULL DEFAULT NULL,
  `produit_idProduit` INT NOT NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`idCatalogue`, `produit_idProduit`),
  INDEX `fk_catalogue_produit1_idx` (`produit_idProduit` ASC) VISIBLE,
  CONSTRAINT `fk_catalogue_produit1`
    FOREIGN KEY (`produit_idProduit`)
    REFERENCES `produit` (`idProduit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(45) NULL DEFAULT NULL,
  `visible` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `packproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `packproduit` (
  `idPackProduit` INT NOT NULL AUTO_INCREMENT,
  `nomPack` VARCHAR(45) NULL DEFAULT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `photoURL` VARCHAR(1000) NULL DEFAULT NULL,
  `visible` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPackProduit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pointramassage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointramassage` (
  `idPointRamassage` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `visible` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPointRamassage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pannier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pannier` (
  `idpannier` INT NOT NULL AUTO_INCREMENT,
  `prix` DOUBLE NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `idPointRamassage` INT NULL DEFAULT NULL,
  `idClient` INT NULL DEFAULT NULL,
  `moyenPaiement` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idpannier`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idPointRamassage_idx` (`idPointRamassage` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `client` (`idClient`),
  CONSTRAINT `idPointRamassage`
    FOREIGN KEY (`idPointRamassage`)
    REFERENCES `pointramassage` (`idPointRamassage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ligneproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligneproduit` (
  `idLigneProduit` INT NOT NULL AUTO_INCREMENT,
  `quantiteCommande` INT NULL DEFAULT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `idProduit` INT NULL DEFAULT NULL,
  `idPack` INT NULL DEFAULT NULL,
  `idPannier` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idLigneProduit`),
  INDEX `idPack_idx` (`idPack` ASC) VISIBLE,
  INDEX `idPannier_idx` (`idPannier` ASC) VISIBLE,
  INDEX `idProduit_idx` (`idProduit` ASC) VISIBLE,
  CONSTRAINT `idPack`
    FOREIGN KEY (`idPack`)
    REFERENCES `packproduit` (`idPackProduit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPannier`
    FOREIGN KEY (`idPannier`)
    REFERENCES `pannier` (`idpannier`),
  CONSTRAINT `idProduit`
    FOREIGN KEY (`idProduit`)
    REFERENCES `produit` (`idProduit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producteur` (
  `idProducteur` INT NOT NULL AUTO_INCREMENT,
  `nomProducteur` VARCHAR(45) NULL DEFAULT NULL,
  `frequenceProduction` INT NULL DEFAULT NULL,
  `volumeProduction` INT NULL DEFAULT NULL,
  `conditionnement` VARCHAR(45) NULL DEFAULT NULL,
  `saisonnier` VARCHAR(45) NULL DEFAULT NULL,
  `valide` INT NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `logitude` DOUBLE NULL DEFAULT NULL,
  `visible` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProducteur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `producteur_has_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producteur_has_produit` (
  `Producteur_idProducteur` INT NOT NULL AUTO_INCREMENT,
  `Produit_idProduit` INT NOT NULL,
  PRIMARY KEY (`Producteur_idProducteur`, `Produit_idProduit`),
  INDEX `fk_Producteur_has_Produit_Producteur1_idx` (`Producteur_idProducteur` ASC) VISIBLE,
  INDEX `fk_Producteur_has_Produit_Produit1_idx` (`Produit_idProduit` ASC) VISIBLE,
  CONSTRAINT `fk_Producteur_has_Produit_Producteur1`
    FOREIGN KEY (`Producteur_idProducteur`)
    REFERENCES `producteur` (`idProducteur`),
  CONSTRAINT `fk_Producteur_has_Produit_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `produit` (`idProduit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ropert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ropert` (
  `idManager` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idManager`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
